/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as DoptApi from "../../../../../api";
import * as core from "../../../../../core";

export const IntentRequest: core.serialization.Schema<
    serializers.IntentRequest.Raw,
    Omit<DoptApi.IntentRequest, "userIdentifier" | "groupIdentifier" | "version" | "tag" | "force">
> = core.serialization.object({});

export declare namespace IntentRequest {
    interface Raw {}
}
