/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../..";

export interface GetFlowRequest {
    version?: number;
    tag?: DoptApi.GetFlowRequestTag;
    include?: "block";
    userIdentifier: string;
    groupIdentifier?: string;
}
