/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetFlowRequest {
    version: number;
    include?: "block";
    userIdentifier: string;
    groupIdentifier?: string;
}
