/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../..";

export interface IntentRequest {
    version?: number;
    tag?: DoptApi.IntentRequestTag;
    userIdentifier: string;
    groupIdentifier?: string;
    force?: boolean;
}
