/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BlockTransitionQueryString {
    transitions: string[];
    version: number;
    userIdentifier: string;
    groupIdentifier?: string;
}
