/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FlowIntentRequestParamsIntent = "finish" | "stop" | "reset" | "start";

export const FlowIntentRequestParamsIntent = {
    Finish: "finish",
    Stop: "stop",
    Reset: "reset",
    Start: "start",
} as const;
