/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FlowIntentQueryStringTag = "uncommitted" | "latest";

export const FlowIntentQueryStringTag = {
    Uncommitted: "uncommitted",
    Latest: "latest",
} as const;
