/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "..";

export interface FlowIntentRequestParams {
    uid: string;
    intent: DoptApi.FlowIntentRequestParamsIntent;
}
