/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "..";

export interface FlowIntentQueryString {
    version?: number;
    tag?: DoptApi.FlowIntentQueryStringTag;
    userIdentifier: string;
    groupIdentifier?: string;
    force?: boolean;
}
