/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "..";

export type GetBlockResponseFieldsItem =
    | DoptApi.GetBlockResponseFieldsItemGetBlockResponseFieldsItem
    | DoptApi.GetBlockResponseFieldsItemGetBlockResponseFieldsItem
    | DoptApi.GetBlockResponseFieldsItemGetBlockResponseFieldsItem
    | DoptApi.GetBlockResponseFieldsItemGetBlockResponseFieldsItem;
