/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetBlockResponseType = "custom" | "modal" | "checklist" | "checklistItem" | "tour" | "tourItem";

export const GetBlockResponseType = {
    Custom: "custom",
    Modal: "modal",
    Checklist: "checklist",
    ChecklistItem: "checklistItem",
    Tour: "tour",
    TourItem: "tourItem",
} as const;
