/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "..";

export interface GetBlockResponse {
    kind: "block";
    uid: string;
    sid: string;
    version: number;
    state: DoptApi.GetBlockResponseState;
    containerUid?: string;
    transitioned: Record<string, boolean>;
    type: DoptApi.GetBlockResponseType;
    fields: DoptApi.GetBlockResponseFieldsItem[];
}
