/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetFlowResponseBlocksItemFieldsItemGetFlowResponseBlocksItemFieldsItem {
    sid: string;
    type: "richText";
    value?: Record<string, unknown>[];
}
