/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetFlowQueryStringTag = "uncommitted" | "latest";

export const GetFlowQueryStringTag = {
    Uncommitted: "uncommitted",
    Latest: "latest",
} as const;
