/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetFlowResponseBlocksItemType =
    | "custom"
    | "card"
    | "modal"
    | "checklist"
    | "checklistItem"
    | "hints"
    | "hintsItem"
    | "tour"
    | "tourItem";

export const GetFlowResponseBlocksItemType = {
    Custom: "custom",
    Card: "card",
    Modal: "modal",
    Checklist: "checklist",
    ChecklistItem: "checklistItem",
    Hints: "hints",
    HintsItem: "hintsItem",
    Tour: "tour",
    TourItem: "tourItem",
} as const;
