/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetFlowRequestTag = "uncommitted" | "latest";

export const GetFlowRequestTag = {
    Uncommitted: "uncommitted",
    Latest: "latest",
} as const;
