/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "..";

export interface GetFlowResponse {
    kind: "flow";
    type: "flow";
    uid: string;
    sid: string;
    version: number;
    state: DoptApi.GetFlowResponseState;
    blocks?: DoptApi.GetFlowResponseBlocksItem[];
}
