/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "..";

export type GetFlowResponseBlocksItemFieldsItem =
    | DoptApi.GetFlowResponseBlocksItemFieldsItemGetFlowResponseBlocksItemFieldsItem
    | DoptApi.GetFlowResponseBlocksItemFieldsItemGetFlowResponseBlocksItemFieldsItem
    | DoptApi.GetFlowResponseBlocksItemFieldsItemGetFlowResponseBlocksItemFieldsItem
    | DoptApi.GetFlowResponseBlocksItemFieldsItemGetFlowResponseBlocksItemFieldsItem;
