/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type IntentRequestTag = "uncommitted" | "latest";

export const IntentRequestTag = {
    Uncommitted: "uncommitted",
    Latest: "latest",
} as const;
