/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const BlockTransitionRequestBody: core.serialization.ObjectSchema<
    serializers.BlockTransitionRequestBody.Raw,
    DoptApi.BlockTransitionRequestBody
> = core.serialization.object({});

export declare namespace BlockTransitionRequestBody {
    interface Raw {}
}
