/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const BlockTransitionRequestParams: core.serialization.ObjectSchema<
    serializers.BlockTransitionRequestParams.Raw,
    DoptApi.BlockTransitionRequestParams
> = core.serialization.object({
    uid: core.serialization.string(),
});

export declare namespace BlockTransitionRequestParams {
    interface Raw {
        uid: string;
    }
}
