/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const FlowIntentQueryStringTag: core.serialization.Schema<
    serializers.FlowIntentQueryStringTag.Raw,
    DoptApi.FlowIntentQueryStringTag
> = core.serialization.enum_(["uncommitted", "latest"]);

export declare namespace FlowIntentQueryStringTag {
    type Raw = "uncommitted" | "latest";
}
