/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const FlowIntentRequestBody: core.serialization.ObjectSchema<
    serializers.FlowIntentRequestBody.Raw,
    DoptApi.FlowIntentRequestBody
> = core.serialization.object({});

export declare namespace FlowIntentRequestBody {
    interface Raw {}
}
