/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const FlowIntentRequestParams: core.serialization.ObjectSchema<
    serializers.FlowIntentRequestParams.Raw,
    DoptApi.FlowIntentRequestParams
> = core.serialization.object({
    sid: core.serialization.string(),
    intent: core.serialization.lazy(async () => (await import("..")).FlowIntentRequestParamsIntent),
});

export declare namespace FlowIntentRequestParams {
    interface Raw {
        sid: string;
        intent: serializers.FlowIntentRequestParamsIntent.Raw;
    }
}
