/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const GetBlockResponseFieldsItemNumber: core.serialization.ObjectSchema<
    serializers.GetBlockResponseFieldsItemNumber.Raw,
    DoptApi.GetBlockResponseFieldsItemNumber
> = core.serialization.object({
    sid: core.serialization.string(),
    value: core.serialization.number().optional(),
});

export declare namespace GetBlockResponseFieldsItemNumber {
    interface Raw {
        sid: string;
        value?: number | null;
    }
}
