/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const GetBlockQueryString: core.serialization.ObjectSchema<
    serializers.GetBlockQueryString.Raw,
    DoptApi.GetBlockQueryString
> = core.serialization.object({
    version: core.serialization.number(),
    userIdentifier: core.serialization.string(),
});

export declare namespace GetBlockQueryString {
    interface Raw {
        version: number;
        userIdentifier: string;
    }
}
