/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const GetBlockResponseFieldsItem: core.serialization.Schema<
    serializers.GetBlockResponseFieldsItem.Raw,
    DoptApi.GetBlockResponseFieldsItem
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(
        async () => (await import("..")).GetBlockResponseFieldsItemGetBlockResponseFieldsItem
    ),
    core.serialization.lazyObject(
        async () => (await import("..")).GetBlockResponseFieldsItemGetBlockResponseFieldsItem
    ),
    core.serialization.lazyObject(
        async () => (await import("..")).GetBlockResponseFieldsItemGetBlockResponseFieldsItem
    ),
    core.serialization.lazyObject(
        async () => (await import("..")).GetBlockResponseFieldsItemGetBlockResponseFieldsItem
    ),
]);

export declare namespace GetBlockResponseFieldsItem {
    type Raw =
        | serializers.GetBlockResponseFieldsItemGetBlockResponseFieldsItem.Raw
        | serializers.GetBlockResponseFieldsItemGetBlockResponseFieldsItem.Raw
        | serializers.GetBlockResponseFieldsItemGetBlockResponseFieldsItem.Raw
        | serializers.GetBlockResponseFieldsItemGetBlockResponseFieldsItem.Raw;
}
