/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const GetBlockResponseType: core.serialization.Schema<
    serializers.GetBlockResponseType.Raw,
    DoptApi.GetBlockResponseType
> = core.serialization.enum_(["custom", "modal", "checklist", "checklistItem", "tour", "tourItem"]);

export declare namespace GetBlockResponseType {
    type Raw = "custom" | "modal" | "checklist" | "checklistItem" | "tour" | "tourItem";
}
