/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const GetFlowResponse: core.serialization.ObjectSchema<
    serializers.GetFlowResponse.Raw,
    DoptApi.GetFlowResponse
> = core.serialization.object({
    kind: core.serialization.stringLiteral("flow"),
    type: core.serialization.stringLiteral("flow"),
    uid: core.serialization.string(),
    sid: core.serialization.string(),
    version: core.serialization.number(),
    state: core.serialization.lazyObject(async () => (await import("..")).GetFlowResponseState),
    blocks: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).GetFlowResponseBlocksItem))
        .optional(),
});

export declare namespace GetFlowResponse {
    interface Raw {
        kind: "flow";
        type: "flow";
        uid: string;
        sid: string;
        version: number;
        state: serializers.GetFlowResponseState.Raw;
        blocks?: serializers.GetFlowResponseBlocksItem.Raw[] | null;
    }
}
