/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const GetFlowRequestParams: core.serialization.ObjectSchema<
    serializers.GetFlowRequestParams.Raw,
    DoptApi.GetFlowRequestParams
> = core.serialization.object({
    sid: core.serialization.string(),
});

export declare namespace GetFlowRequestParams {
    interface Raw {
        sid: string;
    }
}
