/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const GetFlowResponseBlocksItemFieldsItemString: core.serialization.ObjectSchema<
    serializers.GetFlowResponseBlocksItemFieldsItemString.Raw,
    DoptApi.GetFlowResponseBlocksItemFieldsItemString
> = core.serialization.object({
    sid: core.serialization.string(),
    value: core.serialization.string().optional(),
});

export declare namespace GetFlowResponseBlocksItemFieldsItemString {
    interface Raw {
        sid: string;
        value?: string | null;
    }
}
