/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const GetFlowResponseBlocksItemState: core.serialization.ObjectSchema<
    serializers.GetFlowResponseBlocksItemState.Raw,
    DoptApi.GetFlowResponseBlocksItemState
> = core.serialization.object({
    active: core.serialization.boolean(),
    entered: core.serialization.boolean(),
    exited: core.serialization.boolean(),
});

export declare namespace GetFlowResponseBlocksItemState {
    interface Raw {
        active: boolean;
        entered: boolean;
        exited: boolean;
    }
}
