/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const GetFlowQueryString: core.serialization.ObjectSchema<
    serializers.GetFlowQueryString.Raw,
    DoptApi.GetFlowQueryString
> = core.serialization.object({
    version: core.serialization.number(),
    include: core.serialization.stringLiteral("block").optional(),
    userIdentifier: core.serialization.string(),
    groupIdentifier: core.serialization.string().optional(),
});

export declare namespace GetFlowQueryString {
    interface Raw {
        version: number;
        include?: "block" | null;
        userIdentifier: string;
        groupIdentifier?: string | null;
    }
}
