/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const GetFlowResponseBlocksItemFieldsItem: core.serialization.Schema<
    serializers.GetFlowResponseBlocksItemFieldsItem.Raw,
    DoptApi.GetFlowResponseBlocksItemFieldsItem
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(
        async () => (await import("..")).GetFlowResponseBlocksItemFieldsItemGetFlowResponseBlocksItemFieldsItem
    ),
    core.serialization.lazyObject(
        async () => (await import("..")).GetFlowResponseBlocksItemFieldsItemGetFlowResponseBlocksItemFieldsItem
    ),
    core.serialization.lazyObject(
        async () => (await import("..")).GetFlowResponseBlocksItemFieldsItemGetFlowResponseBlocksItemFieldsItem
    ),
    core.serialization.lazyObject(
        async () => (await import("..")).GetFlowResponseBlocksItemFieldsItemGetFlowResponseBlocksItemFieldsItem
    ),
]);

export declare namespace GetFlowResponseBlocksItemFieldsItem {
    type Raw =
        | serializers.GetFlowResponseBlocksItemFieldsItemGetFlowResponseBlocksItemFieldsItem.Raw
        | serializers.GetFlowResponseBlocksItemFieldsItemGetFlowResponseBlocksItemFieldsItem.Raw
        | serializers.GetFlowResponseBlocksItemFieldsItemGetFlowResponseBlocksItemFieldsItem.Raw
        | serializers.GetFlowResponseBlocksItemFieldsItemGetFlowResponseBlocksItemFieldsItem.Raw;
}
