/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const GetFlowResponseState: core.serialization.ObjectSchema<
    serializers.GetFlowResponseState.Raw,
    DoptApi.GetFlowResponseState
> = core.serialization.object({
    stopped: core.serialization.boolean(),
    started: core.serialization.boolean(),
    finished: core.serialization.boolean(),
});

export declare namespace GetFlowResponseState {
    interface Raw {
        stopped: boolean;
        started: boolean;
        finished: boolean;
    }
}
