/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const GetFlowResponseBlocksItemFieldsItemRichText: core.serialization.ObjectSchema<
    serializers.GetFlowResponseBlocksItemFieldsItemRichText.Raw,
    DoptApi.GetFlowResponseBlocksItemFieldsItemRichText
> = core.serialization.object({
    sid: core.serialization.string(),
    value: core.serialization
        .list(core.serialization.record(core.serialization.string(), core.serialization.unknown()))
        .optional(),
});

export declare namespace GetFlowResponseBlocksItemFieldsItemRichText {
    interface Raw {
        sid: string;
        value?: Record<string, unknown>[] | null;
    }
}
