/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const GetFlowResponseBlocksItemType: core.serialization.Schema<
    serializers.GetFlowResponseBlocksItemType.Raw,
    DoptApi.GetFlowResponseBlocksItemType
> = core.serialization.enum_(["custom", "card", "modal", "checklist", "checklistItem", "tour", "tourItem"]);

export declare namespace GetFlowResponseBlocksItemType {
    type Raw = "custom" | "card" | "modal" | "checklist" | "checklistItem" | "tour" | "tourItem";
}
