/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const HealthCheckResponseBody: core.serialization.ObjectSchema<
    serializers.HealthCheckResponseBody.Raw,
    DoptApi.HealthCheckResponseBody
> = core.serialization.object({
    application: core.serialization.string(),
    status: core.serialization.number(),
});

export declare namespace HealthCheckResponseBody {
    interface Raw {
        application: string;
        status: number;
    }
}
