/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const IntentRequestIntent: core.serialization.Schema<
    serializers.IntentRequestIntent.Raw,
    DoptApi.IntentRequestIntent
> = core.serialization.enum_(["finish", "stop", "reset", "start"]);

export declare namespace IntentRequestIntent {
    type Raw = "finish" | "stop" | "reset" | "start";
}
