/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const UserIdentifierParams: core.serialization.ObjectSchema<
    serializers.UserIdentifierParams.Raw,
    DoptApi.UserIdentifierParams
> = core.serialization.object({
    userIdentifier: core.serialization.string(),
    groupIdentifier: core.serialization.string().optional(),
});

export declare namespace UserIdentifierParams {
    interface Raw {
        userIdentifier: string;
        groupIdentifier?: string | null;
    }
}
