/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Blocks } from "./api/resources/blocks/client/Client";
import { Flows } from "./api/resources/flows/client/Client";

export declare namespace DoptApiClient {
    interface Options {
        environment?: core.Supplier<environments.DoptApiEnvironment | string>;
        apiKey: core.Supplier<string>;
    }
}

export class DoptApiClient {
    constructor(protected readonly options: DoptApiClient.Options) {}

    protected _blocks: Blocks | undefined;

    public get blocks(): Blocks {
        return (this._blocks ??= new Blocks(this.options));
    }

    protected _flows: Flows | undefined;

    public get flows(): Flows {
        return (this._flows ??= new Flows(this.options));
    }
}
