/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TransitionRequest {
    transitions?: string | string[];
    userIdentifier: string;
    groupIdentifier?: string;
    version: number;
}
