/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TransitionRequest {
    transitions?: string | string[];
    version: number;
    userIdentifier: string;
    groupIdentifier?: string;
}
